config/routes.rb
Rails.application.routes.draw do
  # Define custom routes for the search action
  get "books/search", to: "books#search", as: :search_books
  post "books/search", to: "books#search"

  # Uncomment this line for PWA support
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # We don't need the service-worker route since we're not implementing offline functionality
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get "up" => "rails/health#show", as: :rails_health_check

  root "books#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates :isbn, presence: true, uniqueness: true
end

app/models/book_details.rb
class BookDetails
  include ActiveModel::Model

  attr_accessor :title, :author, :series, :atos_book_level,
                :ar_points, :interest_level, :word_count

  validates :title, presence: true
  validates :author, presence: true
  validates :series, presence: true

  # AR details group validations
  validates :atos_book_level, :ar_points, :interest_level, :word_count,
    presence: true,
    if: :ar_details_present?

  validates :atos_book_level,
    numericality: {
      greater_than_or_equal_to: 1,
      less_than_or_equal_to: 9.9
    },
    if: :atos_book_level

  validates :ar_points,
    numericality: { greater_than_or_equal_to: 0 },
    if: :ar_points

  validates :word_count,
    numericality: {
      only_integer: true,
      greater_than: 0
    },
    if: :word_count


  private

    def ar_details_present?
      atos_book_level.present? ||
      ar_points.present? ||
      interest_level.present? ||
      word_count.present?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def search
    @books = []
    query = params[:query]

    if query.present?

      query = query.gsub(/[“”]/, '"')
      Rails.logger.info "search_arbookfind for query = #{query}"

      @books = TimeHelper.time_function("search_arbookfind for query = #{query}") do
        BookfindService.instance.search(query)
      end
    elsif params[:isbns].present?
      isbns = params[:isbns].split(",")

      isbn_threads = isbns.map do |isbn|
        Thread.new do
          TimeHelper.time_function("search_arbookfind for ISBN #{isbn}") do
            BookfindService.instance.search_by_isbn(isbn)
          end
        end
      end
      @books = isbn_threads.map(&:value).flatten
    end

    render :search
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/search.html.erb
<main>

<%= form_with url: search_books_path, method: :get, local: true, data: { turbo: false } do |f| %>
  <div style="display: grid; grid-template-columns: 1fr auto; gap: 0.5rem;">
    <%= f.text_field :query, value: params[:query], placeholder: "Title, author, series, ISBN..." %>
    <%= f.submit "Search", onclick: "this.value='Searching...'; this.disabled=true; this.form.submit();" %>
  </div>
<% end %>

  <!-- Results -->
  <% if @books.any? %>
    <div class="table-wrapper" style="width: 100%;" data-controller="table" data-table-target="wrapper">
      <table data-table-target="table" style="width: 100%;">
        <thead>
          <tr>
            <th>Title</th>
            <th>Author</th>
            <th>Series</th>
            <th>Interest</th>
            <th>Level</th>
            <th>Points</th>
            <th>Word Count</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= book.title %></td>
              <td><%= book.author %></td>
               <td><%= book.series %></td>
              <td data-tooltip="<%= case book.interest_level
                # UK codes
                when 'LY' then 'Lower Years: Ages 5-8'
                when 'MY' then 'Middle Years: Ages 9-11'
                when 'MY+' then 'Middle Years Plus: Ages 12-13'
                when 'UY' then 'Upper Years: Ages 14+'
                # US codes
                when 'LG' then 'Lower Grades: Ages 5-8'
                when 'MG' then 'Middle Grades: Ages 9-11'
                when 'MG+' then 'Middle Grades Plus: Ages 12-13'
                when 'UG' then 'Upper Grades: Ages 14+'
                else 'Unknown Interest Level'
                end %>">
              <%= book.interest_level %>
              <td><%= book.atos_book_level %></td>
              <td><%= book.ar_points %></td>
              <td><%= book.word_count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% elsif params[:query].present? || params[:photos].present? %>
    <p>No matches found</p>
  <% end %>
  
  <hr>

  <!-- ISBN Photo Search -->
<%= form_with url: search_books_path, method: :get, multipart: true, data: { 
  controller: "photo-upload",
  photo_upload_url_value: search_books_path,
  turbo: false 
} do |f| %>
  <div style="display: grid; grid-template-columns: 1fr auto">
    <%= f.file_field :photos, 
        multiple: true,
        accept: 'image/*', 
        style: "display: none;", 
        data: { 
          photo_upload_target: "fileInput",
          action: "change->photo-upload#handleFileChange"
        } %>
    <%= f.submit "Scan Barcode(s)", 
        data: { 
          photo_upload_target: "submitButton",
          action: "click->photo-upload#promptFileSelection"
        },
        onclick: "return false;" %>
  </div>
<% end %>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Book Finder" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%# Add these new meta tags for better iOS support %>
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="BookFinder">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/open-book-icon.ico" type="image/x-icon">
    <link rel="icon" href="/open-book-icon-512.png" type="image/png">
    <link rel="icon" href="/open-book-icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/open-book-icon-180.png">
    <%# Add additional iOS icon sizes %>
    <link rel="apple-touch-icon" sizes="180x180" href="/open-book-icon-180.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/open-book-icon-152.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdn.simplecss.org/simple.min.css"%>
    <%= javascript_importmap_tags %>

  
  </head>

  <body>
    <%= yield %>
  </body>
</html>